test:
  facebook_app_id: 2432040720451361
  facebook_app_secret: ecd2a96dd5da41557adf0f6d4f691ac7
development:
  facebook_app_id: 2432040720451361
  facebook_app_secret: ecd2a96dd5da41557adf0f6d4f691ac7
production:
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
