test:
  facebook_app_id: 2426372711022155
  facebook_app_secret: 8499f49de02b5a529043490d05c6d4f1
development:
  facebook_app_id: 2426372711022155
  facebook_app_secret: 8499f49de02b5a529043490d05c6d4f1
production:
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
