test:
  facebook_app_id: 1369890016521424
  facebook_app_secret: 113e516c55a5ddc2c4e6ae7e7ef94db9
  azure_storage_account_name: 'targowisko'
  azure_storage_access_key: 'bFjNfhQ8q3mxw0G/+fgfGDtQE1Sbd1Xqcn9H/n/YY9Bc14Co8kMpnJnGEF/Cf/FwSPfuZEwdQ+IENto/IWn2aQ=='
  azure_container: 'fdkgnvwdjnrtgotrwnilrtgertgrwe'
development:
  facebook_app_id: 1369890016521424
  facebook_app_secret: 113e516c55a5ddc2c4e6ae7e7ef94db9
  azure_storage_account_name: 'targowisko'
  azure_storage_access_key: 'bFjNfhQ8q3mxw0G/+fgfGDtQE1Sbd1Xqcn9H/n/YY9Bc14Co8kMpnJnGEF/Cf/FwSPfuZEwdQ+IENto/IWn2aQ=='
  azure_container: 'fdkgnvwdjnrtgotrwnilrtgertgrwe'
production:
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  redis_url: <%= ENV['REDISCLOUD_URL'] || ENV['REDIS_URL'] %>
  redis_auth: <%= ENV['REDIS_AUTH'] %>
  azure_storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  azure_storage_access_key: <%= ENV['AZURE_STORAGE_ACCESS_KEY'] %>
  azure_container: <%= ENV['AZURE_CONTAINER'] %>
