test:
  facebook_app_id: 1369890016521424
  facebook_app_secret: 113e516c55a5ddc2c4e6ae7e7ef94db9
development:
  facebook_app_id: 1369890016521424
  facebook_app_secret: 113e516c55a5ddc2c4e6ae7e7ef94db9
production:
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  redis_url: <%= ENV['REDISCLOUD_URL'] || ENV['REDIS_URL'] %>
  redis_auth: <%= ENV['REDIS_AUTH'] %>
